name: CI Pipeline

on:
  push:
    branches: [ "main", "desafio-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run CI Validation Check
        run: echo "Pipeline de CI iniciada e validada com sucesso!"